### ISSUE TITLE
Reset button

### ISSUE THREAD

**Issue by jjfeore** [jjfeore/fourinarow#10]
Add a styled reset button to the main page. When clicked the game should reset.

**Comment by jjfeore** [comment]
Added a reset/refresh button to all the pages. It has an id of "refresh-button".

**Comment by bretladenburg** [comment]
Add an id called "resetBtn" to all corresponding i tags in all three pages as well as adding a javascript function in the app.js file which should do the job.  I've tested it and it clears everything from local storage after a confirm pop up asking if they are sure.

**Comment by jjfeore** [comment]
Did some more work on this. I changed the prompt to something a bit more visually appealing and consistent with the page theme.
