### ISSUE TITLE
Save board state

### ISSUE THREAD

**Issue by jjfeore** [jjfeore/fourinarow#12]
When the page is refreshed or a player returns to the page, it should load the last board state.

**Comment by Chiefautoparts** [comment]
I will be working on this today

**Comment by Chiefautoparts** [comment]
window.onbeforeunload will activate when browser is closed. pretty sure this is the way to save the game on the event of browser closing and not hitting the reset game  button

**Comment by jjfeore** [comment]
Got this working!
