### ISSUE TITLE
Theme Page Functionality

### ISSUE THREAD

**Issue by jjfeore** [jjfeore/fourinarow#9]
1. Theme page should allow user to select a theme, hit the button, and save that into localStorage.customTheme

2. When the user selects a theme, the page should change colors to that theme dynamically

3. If there is a theme in localStorage, the page should load that by default

**Comment by timothy-tran** [comment]
Add functionality to theme page 
Save the custom theme to local storage
In app.js get the custom theme and apply that to the board game

**Comment by jjfeore** [comment]
Got everything working right and set up a pull. If things aren't working as the team intended, we can reopen the issue, but this should be solid.
